### PR TITLE
Handy pyspark scripts to install spark-video for local dev

### PR DESCRIPTION
**Pull request by da-tubi**

### CODE REVIEW

**Comment by da-tubi** [comment]
verified locally on macOS

**Comment by Renkai** [comment]
```
spark-video git:(feature/local_dev) pyspark bin/local_install.py

Running python applications through 'pyspark' is not supported as of Spark 2.0.
Use ./bin/spark-submit <python file>
/Users/renkaige/miniconda/envs/rikai-example/lib/python3.8/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
head: illegal line count -- -1
```
Not work on my mac

**Comment by Renkai** [comment]
> or copy and paste the python code from bin/local_install.py to the pyspark REPL.

Copy paste works

**Comment by da-tubi** [comment]
Thanks for your review. README updated!

**Review by Renkai — APPROVED** [review]

**Pull request merged**
